before_script:
    - /usr/local/bin/composer self-update
    - composer install

phpunit:
  script:
    - php vendor/phpunit/phpunit/phpunit --coverage-text
    - bin/phpunit tests
    - phpunit --coverage-text tests
